server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ECOM_Project
    password: 1212
    driver-class-name: oracle.jdbc.OracleDriver


#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.OracleDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: fK93uNs@7$wLp!zE4^tYvP2d#MqXa8RJbGo0nB5HcLmKcX1UoWr9SzYqTdAeV6Jv
  expirationMs: 86400000

logging:
  level:
    org.springframework.security: DEBUG
