-- Migration: CreateSkuTable
-- Write your SQL here
create table sku(
    sku_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sku_code VARCHAR2(100) not null,
    Description CLOB,
    Product_Id NUMBER not null,
    Base_Price NUMBER(12, 2),
    sale_price Number(12,2),
    is_serialized char(1) default 'N',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_id FOREIGN KEY (Product_Id) REFERENCES product(product_id)

)