-- Migration: Warehouse
-- Write your SQL here
Create table warehouse(
    warehouse_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    warehouse_name VARCHAR2(255) UNIQUE NOT NULL,
    location VARCHAR2(450) NOT NULL,
    description clob
)
