-- Migration: CreateAttributeTable
CREATE TABLE ATTRIBUTE (
                           ATTRIBUTE_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           ATTRIBUTE_NAME VARCHAR2(255) UNIQUE NOT NULL,
                           unit_of_measure VARCHAR2(450),
                           DESCRIPTION CLOB
);

-- Merge (upsert) attribute data to avoid duplicates

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Battery Life' AS ATTRIBUTE_NAME, 'hours' AS unit_of_measure, 'Duration of battery operation without recharging' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Screen Size' AS ATTRIBUTE_NAME, 'inches' AS unit_of_measure, 'Diagonal size of the display screen' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Weight' AS ATTRIBUTE_NAME, 'grams' AS unit_of_measure, 'Weight of the product' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Storage Capacity' AS ATTRIBUTE_NAME, 'GB' AS unit_of_measure, 'Internal storage capacity' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Processor Speed' AS ATTRIBUTE_NAME, 'GHz' AS unit_of_measure, 'CPU clock speed' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'RAM' AS ATTRIBUTE_NAME, 'GB' AS unit_of_measure, 'Memory size' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Camera Resolution' AS ATTRIBUTE_NAME, 'megapixels' AS unit_of_measure, 'Resolution of the camera sensor' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Connectivity' AS ATTRIBUTE_NAME, NULL AS unit_of_measure, 'Type of network or wireless connectivity supported' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Color' AS ATTRIBUTE_NAME, NULL AS unit_of_measure, 'Color of the product' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Warranty Period' AS ATTRIBUTE_NAME, 'months' AS unit_of_measure, 'Duration of product warranty' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Power Consumption' AS ATTRIBUTE_NAME, 'watts' AS unit_of_measure, 'Amount of electrical power consumed' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Dimensions' AS ATTRIBUTE_NAME, 'cm' AS unit_of_measure, 'Physical dimensions (L x W x H)' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Audio Output' AS ATTRIBUTE_NAME, NULL AS unit_of_measure, 'Audio output specifications' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Display Type' AS ATTRIBUTE_NAME, NULL AS unit_of_measure, 'Type of display panel, e.g. OLED, LCD' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);

MERGE INTO ATTRIBUTE a
    USING (SELECT 'Operating System' AS ATTRIBUTE_NAME, NULL AS unit_of_measure, 'Operating system installed on the device' AS DESCRIPTION FROM dual) src
    ON (a.ATTRIBUTE_NAME = src.ATTRIBUTE_NAME)
    WHEN NOT MATCHED THEN
        INSERT (ATTRIBUTE_NAME, unit_of_measure, DESCRIPTION)
            VALUES (src.ATTRIBUTE_NAME, src.unit_of_measure, src.DESCRIPTION);
