 -- Migration: Supplier
-- Write your SQL here
CREATE TABLE Supplier(
    supplier_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    supplier_name VARCHAR2(255) UNIQUE NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    phone VARCHAR2(255) UNIQUE NOT NULL,
    address CLOB NOT NULL

)