-- Migration: Supplier
-- Write your SQL here

CREATE TABLE Supplier (
                          supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          supplier_name VARCHAR2(255) UNIQUE NOT NULL,
                          email VARCHAR2(255) UNIQUE NOT NULL,
                          phone VARCHAR2(255) UNIQUE NOT NULL,
                          address CLOB NOT NULL
);

CREATE TABLE Supplier_Product (
                                  supplier_product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  supplier_id NUMBER NOT NULL,
                                  SKU_ID NUMBER UNIQUE NOT NULL,
                                  Lead_Time_Days NUMBER,
                                  CostPrice NUMBER(18,2),
                                  Status NVARCHAR2(50),
                                  CONSTRAINT fk_supplier
                                      FOREIGN KEY (supplier_id) REFERENCES Supplier(supplier_id) ON DELETE CASCADE,
                                  CONSTRAINT fk_sku
                                      FOREIGN KEY (SKU_ID) REFERENCES SKU(SKU_ID)
);

CREATE TABLE SUPPLIER_PAYMENT_METHOD (
                                         SPM_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                         SUPPLIER_ID NUMBER NOT NULL,
                                         payment_type NVARCHAR2(100) NOT NULL,
                                         BANK NVARCHAR2(100),
                                         ACCOUNT_NUMBER  NVARCHAR2(100) UNIQUE,
                                         QR_IMG BLOB,
                                         CONSTRAINT FK_SUPPLIER_PAYMENT_METHOD_SUPPLIER
                                             FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE CASCADE
);

