

CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR2(255 CHAR) NOT NULL,
                       last_name VARCHAR2(255 CHAR) NOT NULL,
                       email VARCHAR2(255 CHAR) NOT NULL UNIQUE,
                       phone VARCHAR2(255 CHAR) NOT NULL,
                       password VARCHAR2(255 CHAR) NOT NULL,
                       role VARCHAR2(255 CHAR) DEFAULT 'ROLE_USER' NOT NULL
);

