

CREATE TABLE users (
                       user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR2(255 CHAR) NOT NULL,
                       last_name VARCHAR2(255 CHAR) NOT NULL,
                       email VARCHAR2(255 CHAR) NOT NULL UNIQUE,
                       phone VARCHAR2(255 CHAR) NOT NULL,
                       password VARCHAR2(255 CHAR) NOT NULL,
                       role VARCHAR2(255 CHAR) DEFAULT 'ROLE_USER' NOT NULL
);

INSERT INTO users (first_name, last_name, email, phone, password, role)
VALUES (
           'Admin',
           'Test',
           'Admintest@testing.com',
           '123-456-7890',
           '$2a$12$d51lKfOpD/V6gbba3n055.J0iVinURBNa5E6bVfLSwKJ9QExJxxd6',
           'ROLE_ADMIN'
       );