CREATE TABLE location (
                          location_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          warehouse_id  NUMBER NOT NULL,
                          section       VARCHAR2(50 CHAR),
                          aisle         VARCHAR2(50 CHAR),
                          bin           NUMBER,
                          note          VARCHAR2(50 CHAR),
                          CONSTRAINT fk_warehouse
                              FOREIGN KEY (warehouse_id)
                                  REFERENCES warehouse(warehouse_id)
                                  ON DELETE CASCADE
);
