CREATE TABLE Location (
                          location_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          warehouse_id NUMBER NOT NULL,
                          section VARCHAR(255),
                          aisle VARCHAR(255),
                          bin VARCHAR(255),
                          note VARCHAR(255),
                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_location_warehouse FOREIGN KEY (warehouse_id) REFERENCES Warehouse(warehouse_id) ON DELETE CASCADE
);

CREATE TABLE Individual_Unit (
                                 unit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 sku_id NUMBER NOT NULL,
                                 serial_number VARCHAR(450),
                                 current_location_id NUMBER NOT NULL,
                                 CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT fk_individual_unit_location FOREIGN KEY (current_location_id) REFERENCES Location(location_id) ON DELETE CASCADE,
                                 CONSTRAINT fk_individual_unit_sku FOREIGN KEY (sku_id) REFERENCES Sku(sku_id) ON DELETE CASCADE
);

CREATE TABLE Inventory (
                           inventory_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           sku_id NUMBER NOT NULL,
                           quantity NUMBER,
                           current_location_id NUMBER NOT NULL,
                           CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           CONSTRAINT fk_inventory_sku FOREIGN KEY (sku_id) REFERENCES Sku(sku_id) ON DELETE CASCADE,
                           CONSTRAINT fk_inventory_location FOREIGN KEY (current_location_id) REFERENCES Location(location_id) ON DELETE CASCADE
);

CREATE TABLE Barcode (
                         barcode_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         barcode_value VARCHAR(255),
                         sku_id NUMBER,
                         unit_id NUMBER,
                         CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT fk_barcode_sku FOREIGN KEY (sku_id) REFERENCES Sku(sku_id) ON DELETE CASCADE,
                         CONSTRAINT fk_barcode_unit FOREIGN KEY (unit_id) REFERENCES Individual_Unit(unit_id) ON DELETE CASCADE
);

CREATE TABLE Purchase_Request (
                                  request_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  supplier_id NUMBER,
                                  request_date DATE,
                                  expected_delivery_date DATE,
                                  status VARCHAR(255),
                                  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT fk_purchase_request_supplier FOREIGN KEY (supplier_id) REFERENCES Supplier(supplier_id) ON DELETE CASCADE
);

CREATE TABLE Purchase_Item (
                               request_item_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                               request_id NUMBER,
                               sku_id NUMBER,
                               quantity_request NUMBER,
                               CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_purchase_item_request FOREIGN KEY (request_id) REFERENCES Purchase_Request(request_id) ON DELETE CASCADE,
                               CONSTRAINT fk_purchase_item_sku FOREIGN KEY (sku_id) REFERENCES Sku(sku_id) ON DELETE CASCADE
);

CREATE TABLE Supplier_Payment (
                                  payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  supplier_id NUMBER,
                                  payment_date DATE,
                                  request_id NUMBER,
                                  amount NUMBER(18,2),
                                  spm_id NUMBER,
                                  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                  CONSTRAINT fk_supplier_payment_supplier FOREIGN KEY (supplier_id) REFERENCES Supplier(supplier_id) ON DELETE CASCADE,
                                  CONSTRAINT fk_supplier_payment_spm FOREIGN KEY (spm_id) REFERENCES Supplier_Payment_Method(spm_id) ON DELETE CASCADE,
                                  CONSTRAINT fk_supplier_payment_request FOREIGN KEY (request_id) REFERENCES Purchase_Request(request_id) ON DELETE CASCADE
);

CREATE TABLE Supplier_Payment_Invoice (
                                          payment_invoice_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                          payment_id NUMBER,
                                          invoice_number NUMBER,
                                          invoice_date DATE,
                                          CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                          CONSTRAINT fk_supplier_invoice_payment FOREIGN KEY (payment_id) REFERENCES Supplier_Payment(payment_id) ON DELETE CASCADE

    -- invoice_id FK removed: invoice_id column is not declared
);

CREATE TABLE Product_Arrival (
                                 arrival_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                 request_id NUMBER,
                                 payment_id NUMBER,
                                 invoice_number NUMBER,
                                 arrival_date DATE,
                                 received_by NUMBER,
                                 CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 CONSTRAINT fk_product_arrival_request FOREIGN KEY (request_id) REFERENCES Purchase_Request(request_id) ON DELETE CASCADE,
                                 CONSTRAINT fk_product_arrival_payment FOREIGN KEY (payment_id) REFERENCES Supplier_Payment(payment_id) ON DELETE CASCADE,
                                 CONSTRAINT fk_product_arrival_received FOREIGN KEY (received_by) REFERENCES users(user_id) ON DELETE CASCADE
    -- warehouse_id, invoice_id FKs removed due to missing columns
);

CREATE TABLE Product_Item_Arrival (
                                      pia_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                      arrival_id NUMBER NOT NULL,
                                      sku_id NUMBER NOT NULL,
                                      quantity_received NUMBER,
                                      note VARCHAR(255),
                                      CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                      CONSTRAINT fk_item_arrival_arrival FOREIGN KEY (arrival_id) REFERENCES Product_Arrival(arrival_id) ON DELETE CASCADE,
                                      CONSTRAINT fk_item_arrival_sku FOREIGN KEY (sku_id) REFERENCES Sku(sku_id) ON DELETE CASCADE
);
