CREATE TABLE Checkout_Product_SN (
                                  checkout_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                  sku VARCHAR2(255) NOT NULL,
                                  serial_number VARCHAR2(450) NOT NULL,
                                  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Checkout_Product_NonSerial (
                                            checkout_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                            sku VARCHAR2(255) NOT NULL,
                                            quantity NUMBER DEFAULT 1 NOT NULL,
                                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                                            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Remove_Product_Serialized (
                                           remove_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                           sku VARCHAR2(255) NOT NULL,
                                           serial_number VARCHAR2(450) NOT NULL,
                                           removed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE Remove_Product_NonSerial (
                                          remove_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                                          sku VARCHAR2(255) NOT NULL,
                                          quantity NUMBER DEFAULT 1 NOT NULL,
                                          removed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


