-- Migration: BrandDetail
-- Write your SQL here
CREATE TABLE BRAND (
                       brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name NVARCHAR2(400) NOT NULL,
                       slug NVARCHAR2(400) NOT NULL,
                       description NVARCHAR2(1000) NOT NULL,
                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
