-- Create the BRAND table if it doesn't exist
CREATE TABLE BRAND (
                       brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name NVARCHAR2(400) NOT NULL,
                       slug NVARCHAR2(400) NOT NULL,
                       description NVARCHAR2(1000) NOT NULL,
                       CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Merge (upsert) brand data to avoid duplicates
MERGE INTO BRAND b
    USING (SELECT 'Sony' AS name, 'sony' AS slug, 'Japanese multinational conglomerate corporation specializing in electronics, gaming, and entertainment.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Samsung' AS name, 'samsung' AS slug, 'South Korean multinational electronics company known for smartphones, TVs, and home appliances.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Apple' AS name, 'apple' AS slug, 'American technology company famous for iPhones, MacBooks, and other consumer electronics.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'LG Electronics' AS name, 'lg-electronics' AS slug, 'South Korean electronics company specializing in home appliances and consumer electronics.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Panasonic' AS name, 'panasonic' AS slug, 'Japanese multinational electronics corporation manufacturing a wide range of products including cameras and TVs.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Dell' AS name, 'dell' AS slug, 'American computer technology company focusing on personal computers, servers, and related products.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'HP' AS name, 'hp' AS slug, 'American multinational information technology company that produces printers, laptops, and desktops.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Microsoft' AS name, 'microsoft' AS slug, 'American multinational technology corporation known for software, hardware, and electronics products.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Canon' AS name, 'canon' AS slug, 'Japanese company specializing in imaging and optical products including cameras and printers.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO BRAND b
    USING (SELECT 'Bose' AS name, 'bose' AS slug, 'American company known for audio equipment including speakers, headphones, and sound systems.' AS description FROM dual) src
    ON (b.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);
