-- Migration: CreateCategoryTable
CREATE TABLE category(
                         category_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         name NVARCHAR2(400) NOT NULL,
                         slug NVARCHAR2(400) NOT NULL,
                         description NVARCHAR2(1000) NOT NULL,
                         CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Merge (upsert) category data to avoid duplicates
MERGE INTO category c
    USING (SELECT 'Smartphones' AS name, 'smartphones' AS slug, 'Mobile phones with advanced features and computing capabilities.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Laptops' AS name, 'laptops' AS slug, 'Portable personal computers for work, study, and entertainment.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Televisions' AS name, 'televisions' AS slug, 'Electronic devices for viewing video content on screens.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Cameras' AS name, 'cameras' AS slug, 'Digital and analog devices for capturing photos and videos.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Audio Equipment' AS name, 'audio-equipment' AS slug, 'Devices such as headphones, speakers, and sound systems.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Home Appliances' AS name, 'home-appliances' AS slug, 'Electrical machines used for household tasks like cleaning and cooking.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Wearable Technology' AS name, 'wearable-technology' AS slug, 'Smart devices worn on the body, such as smartwatches and fitness trackers.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Computer Accessories' AS name, 'computer-accessories' AS slug, 'Peripheral devices like keyboards, mice, and external storage.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Gaming Consoles' AS name, 'gaming-consoles' AS slug, 'Electronic devices designed for playing video games.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);

MERGE INTO category c
    USING (SELECT 'Networking Devices' AS name, 'networking-devices' AS slug, 'Equipment such as routers, modems, and switches for internet connectivity.' AS description FROM dual) src
    ON (c.slug = src.slug)
    WHEN NOT MATCHED THEN
        INSERT (name, slug, description) VALUES (src.name, src.slug, src.description);
