-- Migration: CreateProductTable
CREATE TABLE Product (
                         Product_Id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         Product_Name VARCHAR2(450) NOT NULL UNIQUE,
                         Brand_ID NUMBER NOT NULL,
                         Description CLOB,
                         CONSTRAINT fk_brand FOREIGN KEY (Brand_ID) REFERENCES brand(Brand_ID)
);

-- Merge (upsert) product data to avoid duplicates
MERGE INTO Product p
    USING (SELECT 'iPhone 15 Pro' AS Product_Name, 1 AS Brand_ID, 'Apple''s latest flagship smartphone with advanced camera and performance.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'MacBook Pro 16-inch' AS Product_Name, 1 AS Brand_ID, 'High-performance laptop for professionals by Apple.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Galaxy S23 Ultra' AS Product_Name, 2 AS Brand_ID, 'Samsung''s top-tier smartphone with exceptional display and camera features.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Samsung QLED TV 55"' AS Product_Name, 2 AS Brand_ID, '55-inch QLED smart TV with vibrant colors and smart functionality.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Sony Alpha A7 III' AS Product_Name, 3 AS Brand_ID, 'Full-frame mirrorless camera with excellent autofocus and image quality.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Bose QuietComfort 45' AS Product_Name, 4 AS Brand_ID, 'Noise-cancelling wireless headphones with premium sound quality.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Dell XPS 13' AS Product_Name, 5 AS Brand_ID, 'Compact and powerful ultrabook suitable for everyday computing.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Logitech MX Master 3' AS Product_Name, 6 AS Brand_ID, 'Advanced wireless mouse with ergonomic design and multiple device support.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'PlayStation 5' AS Product_Name, 7 AS Brand_ID, 'Sony''s next-generation gaming console with ultra-fast SSD and immersive graphics.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);

MERGE INTO Product p
    USING (SELECT 'Netgear Nighthawk Router' AS Product_Name, 8 AS Brand_ID, 'High-speed WiFi router optimized for gaming and streaming.' AS Description FROM dual) src
    ON (p.Product_Name = src.Product_Name)
    WHEN NOT MATCHED THEN
        INSERT (Product_Name, Brand_ID, Description) VALUES (src.Product_Name, src.Brand_ID, src.Description);
