-- Migration: CreateProductImage
-- Write your SQL here
CREATE TABLE images (
                        Image_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        Product_ID NUMBER NOT NULL,
                        Image BLOB,
                        Alt_Text VARCHAR2(100),
                        Display_Order NUMBER,
                        CONSTRAINT fk_images_product FOREIGN KEY (Product_ID) REFERENCES product(Product_ID)
);
